export const reverseMacronsMap = {
    'α': '\u1FB1',  // ᾱ: GREEK SMALL LETTER ALPHA WITH MACRON
    'Α': '\u1FB9',  // Ᾱ: GREEK CAPITAL LETTER ALPHA WITH MACRON
    'α': '\u03B1\u0304',  // ᾱ: GREEK SMALL LETTER ALPHA WITH MACRON
    'Α': '\u0391\u0304',  // Ᾱ: GREEK CAPITAL LETTER ALPHA WITH MACRON
    'ἀ': '\u1FB1\u0313',  // ᾱ̓: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    'Ἀ': '\u1FB9\u0313',  // Ᾱ̓: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    'ἁ': '\u1FB1\u0314',  // ᾱ̔: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    'Ἁ': '\u1FB9\u0314',  // Ᾱ̔: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    'ά': '\u1FB1\u0301',  // ᾱ́: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING ACUTE ACCENT
    'ὰ': '\u1FB1\u0300',  // ᾱ̀: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GRAVE ACCENT
    'ᾳ': '\u1FB1\u0345',  // ᾱͅ: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GREEK YPOGEGRAMMENI
    
    'ι': '\u1FD1',  // ῑ: GREEK SMALL LETTER IOTA WITH MACRON
    'Ι': '\u1FD9',  // Ῑ: GREEK CAPITAL LETTER IOTA WITH MACRON
    'ι': '\u03B9\u0304',  // ῑ: GREEK SMALL LETTER IOTA WITH MACRON
    'Ι': '\u0399\u0304',  // Ῑ: GREEK CAPITAL LETTER IOTA WITH MACRON
    'ἰ': '\u1FD1\u0313',  // ῑ̓: GREEK SMALL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    'Ἰ': '\u1FD9\u0313',  // Ῑ̓: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    'ἱ': '\u1FD1\u0314',  // ῑ̔: GREEK SMALL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    'Ἱ': '\u1FD9\u0314',  // Ῑ̔: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    'ί': '\u1FD1\u0301',  // ῑ́: GREEK SMALL LETTER IOTA WITH MACRON COMBINING ACUTE ACCENT
    'ϊ': '\u1FD1\u0308',  // ῑ̈: GREEK SMALL LETTER IOTA WITH MACRON COMBINING DIAERESIS
    
    'υ': '\u1FE1',  // ῡ: GREEK SMALL LETTER UPSILON WITH MACRON
    'Υ': '\u1FE9',  // Ῡ: GREEK CAPITAL LETTER UPSILON WITH MACRON
    'υ': '\u03C5\u0304',  // ῡ: GREEK SMALL LETTER UPSILON WITH MACRON
    'Υ': '\u03A5\u0304',  // Ῡ: GREEK CAPITAL LETTER UPSILON WITH MACRON
    'ὑ': '\u1FE1\u0314',  // ῡ̔: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    'Ὑ': '\u1FE9\u0314',  // Ῡ̔: GREEK CAPITAL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    'ύ': '\u1FE1\u0301',  // ῡ́: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING ACUTE ACCENT
    'ϋ': '\u1FE1\u0308',  // ῡ̈: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING DIAERESIS
};

export const reverseVrachysMap = {
    'α': '\u1FB0',  // ᾰ: GREEK SMALL LETTER ALPHA WITH VRACHY
    'Α': '\u1FB8',  // Ᾰ: GREEK CAPITAL LETTER ALPHA WITH VRACHY
    'α': '\u03B1\u0306',  // ᾰ: GREEK SMALL LETTER ALPHA WITH VRACHY
    'Α': '\u0391\u0306',  // Ᾰ: GREEK CAPITAL LETTER ALPHA WITH VRACHY
    'ἀ': '\u1FB0\u0313',  // ᾰ̓: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING COMMA ABOVE
    'Ἀ': '\u1FB8\u0313',  // Ᾰ̓: GREEK CAPITAL LETTER ALPHA WITH VRACHY COMBINING COMMA ABOVE
    'ἁ': '\u1FB0\u0314',  // ᾰ̔: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    'Ἁ': '\u1FB8\u0314',  // Ᾰ̔: GREEK CAPITAL LETTER ALPHA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    'ά': '\u1FB0\u0301',  // ᾰ́: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING ACUTE ACCENT
    'ὰ': '\u1FB0\u0300',  // ᾰ̀: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING GRAVE ACCENT
    
    'ι': '\u1FD0',  // ῐ: GREEK SMALL LETTER IOTA WITH VRACHY
    'Ι': '\u1FD8',  // Ῐ: GREEK CAPITAL LETTER IOTA WITH VRACHY
    'ι': '\u03B9\u0306',  // ῐ: GREEK SMALL LETTER IOTA WITH VRACHY
    'Ι': '\u0399\u0306',  // Ῐ: GREEK CAPITAL LETTER IOTA WITH VRACHY
    'ἰ': '\u1FD0\u0313',  // ῐ̓: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING COMMA ABOVE
    'Ἰ': '\u1FD8\u0313',  // Ῐ̓: GREEK CAPITAL LETTER IOTA WITH VRACHY COMBINING COMMA ABOVE
    'ἱ': '\u1FD0\u0314',  // ῐ̔: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    'Ἱ': '\u1FD8\u0314',  // Ῐ̔: GREEK CAPITAL LETTER IOTA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    'ί': '\u1FD0\u0301',  // ῐ́: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING ACUTE ACCENT
    'ὶ': '\u1FD0\u0300',  // ῐ̀: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING GRAVE ACCENT
    'ϊ': '\u1FD0\u0308',  // ῐ̈: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING DIAERESIS
    
    'υ': '\u1FE0',  // ῠ: GREEK SMALL LETTER UPSILON WITH VRACHY
    'Υ': '\u1FE8',  // Ῠ: GREEK CAPITAL LETTER UPSILON WITH VRACHY
    'υ': '\u03C5\u0306',  // ῠ: GREEK SMALL LETTER UPSILON WITH VRACHY
    'Υ': '\u03A5\u0306',  // Ῠ: GREEK CAPITAL LETTER UPSILON WITH VRACHY
    'ὐ': '\u1FE0\u0313',  // ῠ̓: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING COMMA ABOVE
    'ὑ': '\u1FE0\u0314',  // ῠ̔: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING REVERSED COMMA ABOVE
    'Ὑ': '\u1FE8\u0314',  // Ῠ̔: GREEK CAPITAL LETTER UPSILON WITH VRACHY COMBINING REVERSED COMMA ABOVE
    'ύ': '\u1FE0\u0301',  // ῠ́: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING ACUTE ACCENT
    'ὺ': '\u1FE0\u0300',  // ῠ̀: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING GRAVE ACCENT
    'ῦ': '\u1FE0\u0342',  // ῠ͂: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING GREEK PERISPOMENI
    'ϋ': '\u1FE0\u0308',  // ῠ̈: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING DIAERESIS
    'ύ': '\u1FE0\u0312',  // ῠ̒: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING TURNED COMMA ABOVE
};

